# docker-compose.yml
# NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker-compose -f ./compose/astrbot.yml up -d
services:
  postgres:
    image: postgres:16-alpine
    container_name: kahunaSystemPostgreDatabase
    restart: always
    ports:
      - "6201:5432"
    environment:
      - POSTGRES_DB=kahunabot
      - POSTGRES_USER=kahunabot
      - POSTGRES_PASSWORD=kahunabot
      - TZ='Asia/Shanghai'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - astrbot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kahunabot"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    container_name: kahunaSystemSdeDatabase
    restart: always
    ports:
      - "6202:5432"
    environment:
      - POSTGRES_DB=sde
      - POSTGRES_USER=kahunabot
      - POSTGRES_PASSWORD=kahunabot
      - TZ='Asia/Shanghai'
    volumes:
      - ./sde_data:/var/lib/postgresql/data
    networks:
      - astrbot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kahunabot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: KahunaSystemRedis
    restart: always
    ports:
      - "6202:6379"
    command: redis-server --appendonly yes
    environment:
      - TZ='Asia/Shanghai'
    volumes:
      - ./redis_data:/data
    networks:
      - astrbot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  neo4j:
    image: neo4j:2025.10.1
    container_name: KahunaSystemNeo4j
    restart: always
    ports:
      - "7687:7687"  # Bolt协议
      - "7474:7474"  # HTTP
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/var/lib/neo4j/plugins
      - neo4j_conf:/var/lib/neo4j/conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  astrbot_network:
    driver: bridge